steps:
#
  - name: hashicorp/terraform:light
    entrypoint: terraform
    args: ["init"]

  - name: hashicorp/terraform:light
    entrypoint: terraform
    args: ["plan", "-out=tfplan"]

  - name: hashicorp/terraform:light
    entrypoint: terraform
    args: ["apply", "-auto-approve", "tfplan"]
